os:
    cache:
        type: REDIS
        redis:
            # ip: 10.10.10.181
            ip: localhost
            port: 16379
            password: 'SbtyMveYNfLzTks7H0apCmyStPzWJqjy'
            database: 0
    file:
        type: MINIO
        local:
            base-path: ./uploads

        minio:
            endpoint: http://10.37.131.224:9000
            access-key: admin
            secret-key: password

        aliyun:
            oss:
                endpoint: your-endpoint
                access-key-id: your-access-key-id
                access-key-secret: your-access-key-secret

spring:
    cache:
        type: GENERIC
    data:
        redis:
            host: ${os.cache.redis.ip}
            password: ${os.cache.redis.password}
            port: ${os.cache.redis.port}
            database: ${os.cache.redis.database}
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            # mysql
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://10.37.131.222:3307/lain_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
            username: root
            password: 123456
            # sqlserver
#            driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#            url: jdbc:sqlserver://192.168.1.130:1433;DatabaseName=lain_db;encrypt=false
#            username: sa
#            password: admin123
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            # mysql
            # sqlserver
            validation-query: SELECT 'x'
            test-while-idle: true
            test-on-borrow: true
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                #login-username: admin
                #login-password: admin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: false
                wall:
                    config:
                        multi-statement-allow: true


##多数据源的配置
#dynamic:
#  datasource:
#    slave1:
#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#      url: jdbc:sqlserver://localhost:1433;DatabaseName=renren_security
#      username: sa
#      password: 123456
#    slave2:
#      driver-class-name: org.postgresql.Driver
#      url: jdbc:postgresql://localhost:5432/renren_security
#      username: renren
#      password: 123456